# Generated by Django 3.2.6 on 2021-08-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('amount_stock', models.IntegerField(default=20)),
                ('amount_sold', models.IntegerField(default=10)),
            ],
        ),
    ]
