# Generated by Django 3.2.7 on 2021-11-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock_days_left',
            field=models.IntegerField(null=True),
        ),
    ]
