# Generated by Django 3.2.7 on 2021-12-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_stock_days_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stock_days_left',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
