# Generated by Django 3.2.2 on 2021-05-07 11:18

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class PythonExtension(CreateExtension):
    def __init__(self):
        self.name = 'plpython3u'


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        PythonExtension()
    ]
